apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-app-frontend
  labels:
    app: loan-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loan-app
  template:
    metadata:
      labels:
        app: loan-app
    spec:
      containers:
      - name: loan-app
        image: aa20475/loan-app:v1
        ports:
        - containerPort: 4200
